### PR TITLE
fixed low_vram bug. was testing 24.1 but should have been 6.1 per com…

### PR DESCRIPTION
**Pull request by PBullOfficial**
…ment. line 463

### CODE REVIEW

**Comment by tin2tin** [comment]
Thank you. Hmm... maybe I should expose the value, so people can adjust the value themselves. There was one user with 24 GB of VRAM who was able to generate much longer videos with the low vram setting on.  So I up'ed the value to 24 GB for him. The trade-off is that generating may be slower even if you got a lot of VRAM. 

How does exposing the switch value sound to you? (I'm on 6 GB VRAM only, so I can't test anything above that)

**Comment by PBullOfficial** [comment]
Yes, I think exposing the value could work. Also could have a check option
for low VRAM instead. May I ask why low VRAM setting would result in much
longer videos? I have not been able to reproduce similar videos to the
examples, but I was thinking maybe it was because it wasn’t using CUDA due
to low VRAM.

**Comment by PBullOfficial** [comment]
I noticed low_vram was always true due to being a variable and not running the low_vram() function. Not sure if this was intentional! Also, I keep receiving an error message when running cpu offload of KeyError: text_encoder. Do you know what this could be related to? I tried digging into the dictionaries but got a little lost.

**Comment by tin2tin** [comment]
Thank you for catching the missing (). As I was in the middle of implementing Würstchen, I've manually added your changes already.  As for the vram limit I've set it to 12 GB VRAM(and will at a later point in time implement some setting).

Thanks again. If you do something cool with the add-on, let me know.

**Comment by PBullOfficial** [comment]
Glad to help. Great project, and I look forward to using Würstchen through
the add-on. I mainly have used it for testing. Very useful being integrated
in blender with so many models.

**Pull request closed without merging**
